#pragma once
#include <fmath/physics.h>
#include "State.h"

/*******************************************************************************
 * THERMAL COMPTON SCATTERING MODULE
 * 
 * This module handles thermal (inverse) Compton scattering of photons by a
 * Maxwell-Jüttner electron distribution. There are 4 methods controlled by
 * the parameter comptonMethod in parameters.json:
 * 
 * ============================================================================
 * comptonMethod = 0: TEMPERATURE-BASED PRECOMPUTED TABLES (.dat files)
 * ============================================================================
 *   - Tables are parameterized by P(ν, ν', Te) where Te is electron temperature
 *   - The thermal averaging over Maxwell-Jüttner is done DURING table generation
 *   - Fast at runtime (just interpolation)
 *   - Tables regenerated by calculateRedMatrix=1 using comptonMatrix2()
 *   - Output files: comptonProbMatrix2.dat, tempComptonVec.dat, nuPrimComptonVec.dat, nuComptonVec.dat
 *   - Uses: probInterpolated2() for interpolation
 *   - Called via: thermalCompton2() -> comptonNewNew()
 * 
 * ============================================================================
 * comptonMethod = 1: GAMMA-BASED PRECOMPUTED TABLES (.bin files)
 * ============================================================================
 *   - Tables are parameterized by P(ν, ν', γ) where γ is electron Lorentz factor
 *   - The thermal averaging is done AT RUNTIME (slower but more flexible)
 *   - Binary files (probs.bin, om.bin, omp.bin, nt.bin) are NOT regenerated by code
 *   - Uses: probInterpolated() for single-γ interpolation, probTemp() for thermal average
 *   - Called via: thermalCompton2() -> cNew() and comptonNewNew()
 *   - WARNING: Frequency range is hardcoded in binary files (cannot be changed)
 * 
 * ============================================================================
 * comptonMethod = 2: LOCAL COMPTONIZATION (iterative)
 * ============================================================================
 *   - Full iterative solution of the Kompaneets-like equation locally at each radius
 *   - Iterates until convergence: photon field is self-consistently Comptonized
 *   - Slowest method but most accurate for optically thick regions
 *   - Called via: localCompton() -> comptonNewLocal2()
 *   - Uses comptonMatrix() tables (γ-based) for probability lookup if available
 * 
 * ============================================================================
 * comptonMethod = 3: ON-THE-FLY COMPUTATION
 * ============================================================================
 *   - Computes P(ν, ν', Te) exactly at runtime for each energy
 *   - No precomputed tables needed
 *   - Most flexible (any frequency range) but slowest
 *   - Called via: comptonNewNewNew()
 *   - Uses probexactNew() from probexact.h for exact Klein-Nishina cross section
 * 
 * ============================================================================
 * KEY FUNCTIONS:
 * ============================================================================
 * 
 * TABLE GENERATORS (called when calculateRedMatrix=1):
 *   comptonMatrix()   - Generates γ-based tables: comptonProbMatrix.dat (for method 1)
 *   comptonMatrix2()  - Generates Te-based tables: comptonProbMatrix2.dat (for method 0)
 * 
 * INTERPOLATION FUNCTIONS:
 *   probInterpolated()  - 3D interpolation in (γ, ν', ν) space (method 1)
 *   probInterpolated2() - 3D interpolation in (Te, ν', ν) space (method 0)
 *   probTemp()          - Thermally-averages probInterpolated() at runtime (method 1)
 * 
 * SPECTRUM COMPUTATION:
 *   comptonNewNew()       - Main Compton integral using precomputed tables (methods 0,1)
 *   comptonNewNewNew()    - On-the-fly computation without tables (method 3)
 *   comptonNewLocal()     - Local iterative Compton using γ-tables (method 2)
 *   comptonNewLocal2()    - Simplified local Compton using δ-function approximation
 *   cNew()                - Binary file reader + probability matrix builder (method 1)
 * 
 * HELPER FUNCTIONS:
 *   comptonNewNewPruebaVector() - Pre-builds probability matrix for all (ν', ν) pairs
 *   comptonNewNewNewPruebaVector() - Same but for on-the-fly computation
 *   lumInterp() - Interpolates input luminosity spectrum
 ******************************************************************************/

// Table generators (only called if calculateRedMatrix=1)
void comptonMatrix();    // Generates P(ν,ν',γ) tables -> comptonProbMatrix.dat
void comptonMatrix2();   // Generates P(ν,ν',Te) tables -> comptonProbMatrix2.dat

// Method 1: Binary file reader + probability matrix construction
void cNew(State&,Vector&,Vector);

// Method 0/1: Main spectrum computation using precomputed tables
double comptonNewNew(Vector,Vector,Vector,Vector,Vector,double,double,Vector,size_t);

// Method 3: On-the-fly spectrum computation (no tables)
double comptonNewNewNew(Vector,double,double,Vector,size_t);

// Method 2: Local iterative Comptonization
double comptonNewLocal(Vector,Vector,double,size_t,Vector,size_t);
double comptonNewLocal2(Vector,double,size_t,Vector);

// Legacy/general Compton (not currently used in main workflow)
double compton(Vector,Vector,size_t,Vector,size_t);

// Pre-build probability vectors for efficiency
double comptonNewNewPrueba(Vector p, Vector lumIn, size_t jTemp, Vector energies, size_t jE);
void comptonNewNewPruebaVector(Vector tempVec, Vector nuPrimVec, Vector nuVec, Vector probVec,
			size_t jTemp, Vector energies, size_t jE, Vector& p, double normtemp);
void comptonNewNewNewPruebaVector(size_t jR, Vector energies, size_t jE, Vector& p, double normtemp);

// Interpolation helper
double lumInterp(Vector lum, Vector energies, size_t jE, size_t n, double redE);